name             "long-runner-test-kitchen-fail"
maintainer       "Jack Viers"
maintainer_email "jackcviers@gmail.com"
license          "All rights reserved"
description      "Installs Ros, if it works, but it doesn't because it cuts out"
long_description ""
version          "0.1.0"

depends "apt", "~> 2.3.8"
depends "python", "~> 1.4.6"
depends "java", "~> 1.22.0"
depends "build-essential", "~> 2.0.0"
depends "python", "~> 1.4.6"
depends "java", "~> 1.22.0"
